global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'team-polls'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:5000']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
